# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

builds:
  - binary: starfeed
    main: ./cmd/
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - name_template: "{{.Binary}}_{{.Os}}_{{.Arch}}"

checksum:
  name_template: "checksums.txt"

dockers:
  - image_templates:
      - "atomicmeganerd/starfeed:{{.Version}}-amd64"
    goos: linux
    goarch: amd64
    use: buildx
    dockerfile: docker/Dockerfile.goreleaser
    build_flag_templates:
      - "--platform=linux/amd64"

  - image_templates:
      - "atomicmeganerd/starfeed:{{.Version}}-arm64"
    goos: linux
    goarch: arm64
    use: buildx
    dockerfile: docker/Dockerfile.goreleaser
    build_flag_templates:
      - "--platform=linux/arm64"

docker_manifests:
  - name_template: "atomicmeganerd/starfeed:{{.Version}}"
    image_templates:
      - "atomicmeganerd/starfeed:{{.Version}}-amd64"
      - "atomicmeganerd/starfeed:{{.Version}}-arm64"

  - name_template: "atomicmeganerd/starfeed:latest"
    image_templates:
      - "atomicmeganerd/starfeed:{{.Version}}-amd64"
      - "atomicmeganerd/starfeed:{{.Version}}-arm64"

changelog:
  disable: true
