# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

builds:
  - binary: starfeed
    main: ./cmd/
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - name_template: "{{.Binary}}_{{.Os}}_{{.Arch}}"

checksum:
  name_template: "checksums.txt"

dockers:
  - image_templates:
      - "atomicmeganerd/starfeed:latest"
      - "atomicmeganerd/starfeed:{{.Version}}"
    dockerfile: docker/Dockerfile.goreleaser
