# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

builds:
  - binary: starfeed
    main: ./cmd/
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - name_template: "{{.Binary}}_{{.Os}}_{{.Arch}}"

checksum:
  name_template: "checksums.txt"

dockers_v2:
  - images:
      - "atomicmeganerd/starfeed"
    tags:
      - "{{.Version}}"
      - "latest"
    dockerfile: docker/Dockerfile.goreleaser
    platforms:
      - linux/amd64
      - linux/arm64
    labels:
      "org.opencontainers.image.description": "Starfeed subscribes to RSS feeds for starred GitHub repos"
      "org.opencontainers.image.created": "{{.Date}}"
      "org.opencontainers.image.name": "{{.ProjectName}}"
      "org.opencontainers.image.revision": "{{.FullCommit}}"
      "org.opencontainers.image.version": "{{.Version}}"
      "org.opencontainers.image.source": "https://github.com/atomicmeganerd/starfeed"

retry:
  attempts: 10
  delay: 10s
  max_delay: 5m

changelog:
  disable: true
