---
services:
  starfeed:
    image: localhost/starfeed:latest
    build:
      context: .
      dockerfile: Dockerfile
    command: ["sh", "-c", "sleep 5 && starfeed"]
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      freshrss:
        condition: service_healthy

  freshrss:
    image: freshrss/freshrss:latest
    container_name: freshrss-test
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8080:80"
    tmpfs:
      - /var/www/FreshRSS/data
    environment:
      TZ: UTC
      FRESHRSS_INSTALL: |
        --api-enabled
        --base-url http://localhost:8080
        --default-user ${STARFEED_RSS_USER}
      FRESHRSS_USER: |
        --user ${STARFEED_RSS_USER}
        --password ${STARFEED_RSS_PASS}
        --email test@example.net
        --api-password ${STARFEED_RSS_API_TOKEN}
        --language en
