---

version: '3'

dotenv: [./.env]

env:
  out: bin/starfeed
  src: ./cmd/
  cover_out: cover.out
  cover_xml: cover.xml
  test_xml: test-report.xml
  grc: $(if command -v grc > /dev/null; then echo "grc"; else echo ""; fi)

tasks:
  default:
    cmds:
      - task: test
      - task: lint
      - task: generate-test-reports

  format:
    cmds:
      - go fmt ./...

  build:
    deps: [check-deps]
    cmds:
      - cmd: go build -o {{.out}} {{.src}}
      - cmd: codesign -f -s "RCD Local Development" {{.out}} --deep
        platforms: [darwin] # Only sign the binary on macOS.

  run:
    deps: [build]
    cmds:
      - cmd: ./{{.out}}

  test:
    deps: [build]
    cmds:
      # Colorize the output of the test command if GRC is installed.
      - "{{.grc}} go test $(go list ./... | grep -v utils) -race -v -coverprofile={{.cover_out}}"

  lint:
    deps: [install-tools]
    cmds:
      - golangci-lint run

  clean:
    cmds:
      - rm -f {{.out}} {{.cov_file}} {{.cov_xml_file}} {{.test_xml_file}}

  check-deps:
    cmds:
      - go mod tidy
      - go mod verify

  install-tools:
    cmds:
      - go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
      - go install gotest.tools/gotestsum@latest
      - go install github.com/axw/gocov/gocov@latest
      - go install github.com/AlekSi/gocov-xml@latest

  generate-test-reports:
    deps: [install-tools, test]
    cmds:
      - gotestsum --junitfile={{.test_xml}}
      - gocov convert {{.cover_out}} | gocov-xml > {{.cover_xml}}

  update-deps:
    cmds:
      - go get -u ./...
