---

version: '3'

dotenv: [./.env]

env:
  out: bin/starfeed
  src: ./cmd/
  grc: $(if command -v grc > /dev/null; then echo "grc"; else echo ""; fi)
  cover_out: cover.out
  exclude_packages: "mocks"
  coverage_threshold: 80

tasks:
  default:
    cmds:
      - task: test
      - task: lint
      - task: generate-test-reports

  format:
    cmds:
      - go fmt ./...

  build:
    deps: [check-deps]
    cmds:
      - cmd: go build -o {{.out}} {{.src}}
      - cmd: codesign -f -s "RCD Local Development" {{.out}} --deep
        platforms: [darwin] # Only sign the binary on macOS.

  run:
    deps: [build]
    cmds:
      - cmd: ./{{.out}}

  test:
    deps: [build]
    cmds:
      - |
        {{.grc}} go test $(go list ./... | grep -Ev "{{.exclude_packages}}") \
        -race -v -coverprofile={{.cover_out}}

      - |
        COVERAGE=$(go tool cover -func={{.cover_out}} | grep total: | awk '{print $3}' | sed 's/%//')
        echo "Coverage: $COVERAGE%"
        if [ $(echo "$COVERAGE < {{.coverage_threshold}}" | awk '{if ($1 < $2) print 1; else print 0}') -eq 1 ]; then
          echo "Code coverage ($COVERAGE%) is below the threshold of {{.coverage_threshold}}%"
          exit 1
        fi

  lint:
    deps: [install-tools]
    cmds:
      - golangci-lint run

  clean:
    cmds:
      - rm -f {{.out}} {{.cov_file}} {{.cov_xml_file}} {{.test_xml_file}}

  check-deps:
    cmds:
      - go mod tidy
      - go mod verify

  install-tools:
    cmds:
      - go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
      - go install gotest.tools/gotestsum@latest

  generate-test-reports:
    deps: [install-tools, test]
    cmds:
      - gotestsum --junitfile={{.test_xml}}

  update-deps:
    cmds:
      - go get -u ./...
