---
version: "3"

dotenv: [.env]

env:
  out: bin/starfeed
  src: ./cmd/
  cover_out: cover.out
  exclude_packages: "mocks|cmd"
  CGO_ENABLED: "0"

tasks:
  clean:
    desc: Remove build artifacts
    cmds:
      - rm -f {{.out}} {{.cover_out}}

  check-deps:
    internal: true
    cmds:
      - go mod tidy
      - go mod verify

  build:
    desc: Build the binary
    deps: [check-deps]
    sources:
      - "**/*.go"
      - exclude: "**/*_test.go"
      - go.mod
      - go.sum
    generates:
      - "{{.out}}"
    cmds:
      - cmd: go build -o {{.out}} {{.src}}
      - cmd: codesign -f -s "RCD Local" {{.out}} --deep
        platforms: [darwin]

  run:
    desc: Build and run the app
    deps: [build]
    cmds:
      - "{{.out}}"

  test:
    desc: Run tests with coverage
    cmds:
      - |
        gotestsum --format testdox -- \
        $(go list ./... | grep -Ev "{{.exclude_packages}}") \
        -race -coverprofile={{.cover_out}}
    env:
      CGO_ENABLED: "1"

  lint:
    desc: Lint and auto-fix Go code
    cmds:
      - golangci-lint run --fix ./...
      - go fix ./...
