name: Starfeed CI

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - name: Install Task
        uses: go-task/setup-task@v2

      - name: Install golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          install-mode: "binary"
          version: latest

      - name: Install gotestsum
        run: go install gotest.tools/gotestsum@latest

      - name: Check dependencies
        run: |
          go mod tidy
          git diff --exit-code go.mod go.sum

      - name: Build binary
        run: task build

      - name: Run lints
        run: task lint

      - name: Run tests
        run: task test
